# Compares the freshly built SPIR-V artifacts and the bindings manifest
# against the committed ones (data/shaders/vulkan/) and fails with
# regeneration instructions on any mismatch. This is what makes "the committed
# artifacts match their sources" a build-time guarantee rather than a
# convention (renderer modernization plan, WP-13).
#
# Invoked from the wl_spirv_check target as:
#   cmake -DBUILD_DIR=<binary dir>/shaders -DSOURCE_DIR=<source dir>
#         -DPROGRAMS=<semicolon-separated program list> [-DSPIRV_VAL=spirv-val]
#         -P cmake/CheckSpirvArtifacts.cmake

if (NOT DEFINED BUILD_DIR OR NOT DEFINED SOURCE_DIR OR NOT DEFINED PROGRAMS)
  message(FATAL_ERROR "CheckSpirvArtifacts.cmake needs BUILD_DIR, SOURCE_DIR and PROGRAMS.")
endif()

function(check_artifact RELATIVE_PATH)
  set(BUILT "${BUILD_DIR}/${RELATIVE_PATH}")
  set(COMMITTED "${SOURCE_DIR}/data/shaders/vulkan/${RELATIVE_PATH}")

  if (NOT EXISTS "${COMMITTED}")
    message(FATAL_ERROR
      "Committed SPIR-V artifact is missing: ${COMMITTED}\n"
      "Regenerate the committed artifacts with `ninja update_spirv` (requires glslangValidator)\n"
      "and commit them.")
  endif()

  if (SPIRV_VAL AND RELATIVE_PATH MATCHES "\\.spv$")
    execute_process(
      COMMAND "${SPIRV_VAL}" "${BUILT}"
      RESULT_VARIABLE VALIDATE_RESULT
      OUTPUT_VARIABLE VALIDATE_OUTPUT
      ERROR_VARIABLE VALIDATE_OUTPUT)
    if (NOT VALIDATE_RESULT EQUAL 0)
      message(FATAL_ERROR "spirv-val rejected ${RELATIVE_PATH}:\n${VALIDATE_OUTPUT}")
    endif()
  endif()

  execute_process(
    COMMAND "${CMAKE_COMMAND}" -E compare_files "${BUILT}" "${COMMITTED}"
    RESULT_VARIABLE COMPARE_RESULT)
  if (NOT COMPARE_RESULT EQUAL 0)
    message(FATAL_ERROR
      "The committed artifact '${RELATIVE_PATH}' does not match its shader source.\n"
      "Either the source changed without regenerating, or it was generated by a different\n"
      "glslang version. Regenerate with `ninja update_spirv`, review the diff, and commit.")
  endif()
endfunction()

foreach(PROGRAM IN LISTS PROGRAMS)
  foreach(STAGE IN ITEMS vert frag)
    check_artifact("${PROGRAM}.${STAGE}.spv")
  endforeach()
endforeach()
check_artifact("bindings.json")
